services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:fastauth@db:5432/fastauth

  db:
    image: postgres:15
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fastauth
      - POSTGRES_PASSWORD=fastauth
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt

# How to connect to the database:
# docker exec -it fastauth-db-1 psql -U postgres -d fastauth
